--Part – A:  

SELECT * 
FROM DEPOSIT

--1. Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.  

  SELECT * FROM NEW_DEPOSIT
  SELECT * 
  INTO NEW_DEPOSIT
  FROM DEPOSIT
  WHERE AMOUNT > 3000

--2. Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS.  

  SELECT * FROM NEW_DEPOSIT
  SELECT CNAME , AMOUNT
  INTO MAVDI_CUSTOMERS
  FROM DEPOSIT
  WHERE BNAME = 'MAVDI' 

--3. Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.  

  SELECT * FROM RECENT_DEPOSITS

  SELECT CNAME , AMOUNT
  INTO RECENT_DEPOSITS
  FROM DEPOSIT
  WHERE ADATE > '2025-01-01'

--4. Copy distinct BNAME from DEPOSIT into BRANCH_LIST. 

SELECT * FROM BRANCH_LIST
SELECT DISTINCT BNAME 
INTO BRANCH_LIST
FROM DEPOSIT

--5. Copy top 5 records from DEPOSIT into TOP_DEPOSITS.

SELECT * FROM TOP_DEPOSITS
SELECT TOP(5) *
INTO TOP_DEPOSITS
FROM DEPOSIT

--6. Copy records where AMOUNT between 2000 and 6000 into MID_RANGE. 

  SELECT * FROM MID_RANGE
  SELECT * 
  INTO MID_RANGE
  FROM DEPOSIT
  WHERE AMOUNT BETWEEN 2000 AND 6000

--7. Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH. 

SELECT * FROM UNIQUE_BRANCH
SELECT DISTINCT BNAME
INTO UNIQUE_BRANCH
FROM DEPOSIT

--8. Copy records with NULL branch into NO_BRANCH_ASSIGNED.  

SELECT * FROM NO_BRANCH_ASSIGNED
SELECT *
INTO NO_BRANCH_ASSIGNED
FROM DEPOSIT
WHERE BNAME IS NULL

--9. Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY.

SELECT *
FROM DEPOSIT_COPY

SELECT *
INTO DEPOSIT_COPY
FROM DEPOSIT

SP_RENAME 'DEPOSIT_COPY.AMOUNT','BALANCE'



--10. Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH.  
 
 SELECT *
 FROM SELECTED_BRANCH

 SELECT *
 INTO SELECTED_BRANCH
 FROM DEPOSIT
 WHERE BNAME IN ('MAVDI','BEDI')





--Part – B:  


--11. Create a new table STUDENT_BACKUP from STUDENT without copying any data. 

SELECT *
FROM STUDENT_BACKUP

SELECT *
INTO STUDENT_BACKUP
FROM STUDENT
WHERE 1 = 2

DROP TABLE STUDENT_BACKUP

--12. Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS. 

SELECT *
FROM CS_STUDENTS

SELECT SNAME , CITY
INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH = 'COMPUTER'

--13. Copy top 3 students into TOPPER_LIST. 

SELECT * 
FROM TOPPER_LIST

SELECT TOP(3) *
INTO TOPPER_LIST
FROM STUDENT

--14. Copy distinct CITY from STUDENT into CITY_LIST. 

SELECT * 
FROM CITY_LIST

SELECT DISTINCT CITY
INTO CITY_LIST
FROM STUDENT

--15. Copy records where STDID between 103 and 108 into MID_STUDENTS.

SELECT *
FROM MID_STUDENTS

SELECT *
INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108



--Part – C:  



--16. Copy records with NULL branch into NULL_BRANCH_STUDENTS.


SELECT *
FROM NULL_BRANCH_STUDENTS

SELECT *
INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL

--17. Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY.

SELECT *
FROM STUDENT_COPY

SELECT STDID,SNAME,CITY,SPI AS PERFORMANCE , BRANCH
INTO STUDENT_COPY
FROM STUDENT


--18. Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE. 

SELECT *
FROM CITY_WISE

SELECT * 
INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT','SURAT')

--19. Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS.


SELECT *
FROM NON_CIVIL_STUDENTS

SELECT * 
INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL'

--20. Copy selected columns (SNAME, CITY) from STUDENT table into a new table. 

SELECT *
FROM NEW_TABLE

SELECT SNAME ,CITY
INTO NEW_TABLE
FROM STUDENT


-------------------EXTRA QUESTION------------------

--1. Copy top 5 records where AMOUNT < 1000 into LOW_DEPOSIT.

SELECT *
FROM LOW_DEPOSIT

SELECT TOP(5) *
INTO LOW_DEPOSIT
FROM DEPOSIT
WHERE AMOUNT < 1000

--2. Copy records where AMOUNT >= 5000 into HIGH_DEPOSIT.

SELECT *
FROM HIGH_DEPOSIT

SELECT *
INTO HIGH_DEPOSIT
FROM DEPOSIT
WHERE AMOUNT >= 5000

--3. Copy only ACTNO and CNAME from DEPOSIT into CUSTOMER_DETAILS.

SELECT *
FROM CUSTOMER_DETAILS

SELECT ACTNO , CNAME
INTO CUSTOMER_DETAILS
FROM DEPOSIT

SELECT *
FROM DEPOSIT

--4. Copy records where BNAME = 'BEDI' into BEDI_CUSTOMERS.

SELECT *
FROM BEDI_CUSTOMERS

SELECT *
INTO BEDI_CUSTOMERS
FROM DEPOSIT
WHERE BNAME = 'BEDI'

--5. Copy records where BNAME = 'AJI' into AJI_DEPOSITS.

SELECT *
FROM AJI_DEPOSITS

SELECT *
INTO AJI_DEPOSITS
FROM DEPOSIT
WHERE BNAME = 'AJI'

--6. Copy records where AMOUNT is between 1000 and 4000 into NORMAL_DEPOSITS.

SELECT *
FROM NORMAL_DEPOSITS

SELECT *
INTO NORMAL_DEPOSITS
FROM DEPOSIT
WHERE AMOUNT BETWEEN 1000 AND 4000

DROP TABLE NORMAL_DEPOSITS

--7. Copy records where ADATE < '2025-01-01' into OLD_DEPOSITS.

SELECT *
FROM OLD_DEPOSITS

SELECT *
INTO OLD_DEPOSITS
FROM DEPOSIT
WHERE ADATE < '2025-01-01'

--8. Copy records where BNAME is not equal to 'BEDI' into OTHER_BRANCH_DEPOSITS.

SELECT *
FROM OTHER_BRANCH_DEPOSITS

SELECT *
INTO OTHER_BRANCH_DEPOSITS
FROM DEPOSIT
WHERE BNAME != 'BEDI'

--9. Copy top 3 records with only CNAME and BNAME from DEPOSIT into CUSTOMER_BRANCH

SELECT *
FROM CUSTOMER_BRANCH

SELECT TOP(3) CNAME , BNAME
INTO CUSTOMER_BRANCH
FROM DEPOSIT

--10. Create a table DEPOSIT_EMPTY with the same structure as DEPOSIT but no records.

SELECT *
FROM DEPOSIT_EMPTY

SELECT *
INTO DEPOSIT_EMPTY
FROM DEPOSIT
WHERE 1 = 2

--11. Copy only ACTNO, AMOUNT, and ADATE into TRANSACTION_INFO.

SELECT *
FROM TRANSACTION_INFO

SELECT ACTNO,AMOUNT,ADATE
INTO TRANSACTION_INFO
FROM DEPOSIT

--12. Copy records where AMOUNT = 3000 into EXACT_3000.

SELECT *
FROM  EXACT_3000

SELECT *
INTO EXACT_3000
FROM DEPOSIT
WHERE AMOUNT = 3000